import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";

import { CartProvider } from "./context/cartContext";
import CartSidebar from "./Components/CartSideBar";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Ecommerce Web App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            style={{ backgroundColor: "white" }}
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="flex flex-col flex-1 min-h-screen">
                <Navbar />
                <main className="">
                    <CartProvider>

                        {children}
                        <CartSidebar />
                    </CartProvider>
                </main>
                <Footer />
            </body>
        </html>
    );
}
